# Generated by Django 4.2.1 on 2023-09-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
