# Generated by Django 4.2.1 on 2023-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenApp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=30),
        ),
    ]
