# Generated by Django 4.2.1 on 2023-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenApp', '0004_createmom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmom',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
