# Generated by Django 4.2.1 on 2023-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenApp', '0005_alter_createmom_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='MoM',
        ),
    ]
